# DEMO pipeline for java with gradle

# This pipeline:
  # fetches the repository
  # sets up a host to run
  # builds the application

# name of the pipeline
name: Java build pipeline with Gradle

# list of actions, which triggers the pipeline
on:
  # when a new commit is pushed
  push:
    branches: [ bugBranch, $default-branch ]
    # if README changes, action should not run (no changes in code, which can break)
    paths:
     - '!README.md'
  # when a pull request is opened to the default branch (master or main). This is a environment variable, GitHub knows what to do with it.
  pull_request:
    branches: [ $default-branch ]

# this jobs will be executed during the action (these are the reactions of the actions/event above)
jobs:
  build-on-ubuntu:
    # specify the system(s), which will run the app - sets up also the systems
    runs-on: [ ubuntu-latest]
    
    # define steps to run the app
    steps:
    
    # fetch the repository (pull repository to the target OS)
    - uses: actions/checkout@v1
    
    # validate gradlew script
    - name: Validate Gradle wrapper (gradlew script)
      uses: gradle/wrapper-validation-action@v1
    
    # setup the JDK (java version)
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15 
    
    # list the files of the repo (in the log you will see if something is missing)
    - name: List repo files
      run: ls -a
    
    # grant execute persmission to the gradlew file (otherwise will fail)
    - name: Grant permission
      run: chmod +x gradlew
    
    # use the predefined gradle build action (cache is automated)
    # in reality it`s just run the ./gradlew command
    - name: Gradle build
      uses: gradle/gradle-build-action@v2
      with:
        # ./gradlew build --scan will be executed: build action of gradle and it also provides a short summary about the build as output
        arguments: build --scan
    
    # test report, generated by gradle test task
    # if there is not any test on the path to execute (and gradle is not configured to execute tests, will throw a warning)
    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: Test report
        path: build/reports/tests/test
        
    # run the app (produces output from app)
    - name: Gradle run
      uses: gradle/gradle-build-action@v2
      with:
        arguments: run
        
